name: minecraft_to_speech
description: "A minecraft chat reader."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  bitsdojo_window: ^0.1.6
  flutter:
    sdk: flutter
  menu_bar: ^0.5.3
  window_manager: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
