name: minecraft_to_speech
description: "A minecraft chat reader."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  bitsdojo_window: ^0.1.6
  file_picker: ^8.3.3
  flutter:
    sdk: flutter
  hive: ^4.0.0-dev.2
  isar_flutter_libs: ^4.0.0-dev.13
  menu_bar: ^0.5.3
  path: ^1.9.0
  path_provider: ^2.1.5
  provider: ^6.1.2
  resizable_widget: ^1.0.5
  smooth_list_view: ^2.0.2
  window_manager: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
