name: minecraft_to_speech
description: "A minecraft chat reader."
publish_to: 'none'
version: 2.0.0

environment:
  sdk: ^3.6.2

dependencies:
  aligned_dialog: ^0.0.7
  bitsdojo_window: ^0.1.6
  dynamic_background: ^0.5.0
  extended_text: ^14.2.0
  file_picker: ^8.3.3
  flutter:
    sdk: flutter
  flutter_resizable_container: ^4.0.0
  fluttertoast: ^8.2.12
  hive: ^4.0.0-dev.2
  isar_flutter_libs: ^4.0.0-dev.13
  menu_bar: ^0.5.3
  open_file: ^3.5.10
  path: ^1.9.0
  path_provider: ^2.1.5
  provider: ^6.1.2
  smooth_list_view: ^2.0.2
  win32: ^5.10.1
  window_manager_plus: ^1.0.5

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/launchers/

  fonts:
    - family: Minecraft
      fonts:
        - asset: assets/minecraft.ttf
