name: Deploy to GitHub Releases

on:
  push:
    branches:
      - main

jobs:
  deploy-to-github-releases:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install yq
        run: choco install yq --no-progress
      - name: Get Version from Project File
        id: get-version
        shell: bash
        run: |
          echo "version=$(yq '.version' pubspec.yaml)" >> $GITHUB_OUTPUT
      - name: Install .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Check flutter doctor
        run: flutter doctor
      - name: Build Application
        run: flutter build windows --release
      - name: Create Velopack Release
        run: |
          dotnet tool install -g vpk
          cd build/windows/x64/runner
          vpk download github --repoUrl https://github.com/${{ github.repository }}
          vpk pack --packId MinecraftToSpeech --packVersion ${{ steps.get-version.outputs.version }} --packDir Release --mainExe minecraft_to_speech.exe --packTitle "Minecraft To Speech" --icon ../../../../assets/mts_icon.ico
          vpk upload github --repoUrl https://github.com/${{ github.repository }} --publish --releaseName "Minecraft To Speech ${{ steps.get-version.outputs.version }}" --tag v${{ steps.get-version.outputs.version }}