name: Deploy to GitHub Releases

on:
  push:
    branches:
      - main

jobs:
  get-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.version }}
    env:
      release:
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Get Version from Project File
        id: get-version
        run: echo "version=$(yq '.version' pubspec.yaml)" >> $GITHUB_OUTPUT
      - name: Get Current Version
        run: |
          echo "release=$(curl -qsSL \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "${{ github.api_url }}/repos/${{ github.repository }}/releases/latest" \
          | jq -r .tag_name)" >> $GITHUB_ENV
      - name: Check if version is released
        if: ${{ endsWith(env.release, steps.get-version.outputs.version) }}
        run: |
          echo "Version is already released"
          exit 1
  deploy-to-github-releases:
    runs-on: windows-latest
    needs: get-version
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - name: Build Application
        run: flutter build windows --release
      - name: Install .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x
      - name: Install Velopack
        run: dotnet tool install -g vpk
      - name: Create Velopack Release
        env:
          REPOSITORY: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ needs.get-version.outputs.version }}
        run: |
          cd build/windows/x64/runner
          vpk download github --repoUrl https://github.com/$env:REPOSITORY --token $env:GITHUB_TOKEN
          vpk pack --packId MinecraftToSpeech --packVersion $env:VERSION --packDir Release --mainExe minecraft_to_speech.exe --packTitle "Minecraft To Speech" --icon ../../../../assets/mts_icon.ico
          vpk upload github --repoUrl https://github.com/$env:REPOSITORY --publish --releaseName "Minecraft To Speech $env:VERSION" --tag v$env:VERSION --token $env:GITHUB_TOKEN